### ISSUE TITLE
integer types

### ISSUE THREAD

**Issue by gustedt** [rcseacord/cmp_int#1]
Claiming that this works for "integer types" is kind of weird because it seems that by design it doesn't work for `char` and `bool`. I am not questionning that design, but then this should be made cristal clear in the documentation.

**Comment by AaronBallman** [comment]
This is modelled after the C++20 APIs: https://en.cppreference.com/w/cpp/utility/intcmp

Those APIs explicitly disallow `char` and `bool` and I elected to follow the same principles. Those are not types that should be treated as mathematical types. I agree that the documentation should be made more clear on this.

**Comment by rcseacord** [comment]
Documentation updated.
