### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by gustedt** [rcseacord/cmp_int#2]
your code should stick to one single name prefix

**Comment by rcseacord** [comment]
I think this is referring to the comp_ vs cmp_   This was a mistake as the interface was supposed to match the corresponding C++ interface.  Everything is now cmp_*

**Comment by gustedt** [comment]
Not only that, the `is` prefix is reserved for the standard and a macro like `make_...` that uses the user namespace should not be silently introduced.
