### ISSUE TITLE
cmp_equal is wrong for LHS is negative:

### ISSUE THREAD

**Issue by erichkeane** [rcseacord/cmp_int#5]
See: https://godbolt.org/z/YsdG8Wc7n

If you do:
`cmp_equal(-5, (unsigned)5);`
The result is a true value (or any case where the LHS is negative and the RHS is unsigned).

The probelm is that line 67(`(lhs) < 0 || make_unsigned(lhs) == (rhs) : \` should really be:
`(lhs) >=0 && make_unsigned(lhs) == (rhs) : \`

**Comment by AaronBallman** [comment]
Agreed, this is an issue and that your fix is correct.

**Comment by rcseacord** [comment]
This has been fixed.
