### ISSUE TITLE
side effects of some expressions are doubled 

### ISSUE THREAD

**Issue by ilyakurdyukov** [rcseacord/cmp_int#6]
```c
int x = 0;
puts(cmp_less(x++, 0U) ? "true" : "false");
printf("%d\n", x);
```
Outputs:

    false
    2

Which can be fixed using statement expression, but statement expressions are non-standard.

**Comment by AaronBallman** [comment]
This should be fixed now in 33ce638180fb08bee0b235661b0078f883333907, for some definition of fixed. We reintroduced the implementation using GNU statement expressions and other extensions, but gave a macro to control which interface you get. By default, we prefer the safer interface over the more portable interface.
