### ISSUE TITLE
Uses gcc extension

### ISSUE THREAD

**Issue by gustedt** [rcseacord/cmp_int#7]
`({ })` expressions are a gcc extension.

This is not necessary because all of that can be done in a single expression with nested `?:` conditional.

**Comment by gustedt** [comment]
see #4 on how to avoid the `static_assert` declarations.

**Comment by gustedt** [comment]
Sorry, I had looked into an old version. The `sizeof` trick for `static_assert` is nice.

**Comment by AaronBallman** [comment]
Closing this issue as we already implemented it.
